const Funcionarios = [
	{nombre: 'Pablo+Figueroa', rut: '19478175-K', empresa: 'Frigorifico+Temuco', area: 'Prevencion'},
	{nombre: 'Diego+San+Martin', rut: '19075903-2', empresa: 'Frigorifico+Temuco', area: 'Prevencion'},
	{nombre: 'Louis+Maxilin', rut: '25966879-4', empresa: 'Larrain', area: 'Faena'},
	{nombre: 'Marco+Ignaipil', rut: '20106564-K', empresa: 'Frigorifico+Temuco', area: 'Faena'},
	{nombre: 'Moisés+Gutiérrez', rut: '13114727-9', empresa: 'Larrain', area: 'Trafico+Varas'},
	{nombre: 'Michelet+Prevalus', rut: '26433099-8', empresa: 'Larrain', area: 'Desposte'},
	{nombre: 'Nelson+Gutiérrez', rut: '10431630-1', empresa: 'Galdames', area: 'Faena'},
	{nombre: 'Esteban+Cifuentes', rut: '19858608-0', empresa: 'Galdames', area: 'Faena'},
	{nombre: 'Sergio+Herrera', rut: '19480455-5', empresa: 'Frigorifico+Temuco', area: 'Desposte'},
	{nombre: 'Juan+Gallardo', rut: '9899266-9', empresa: 'Matilde+Contreras', area: 'Desposte'},
	{nombre: 'Sergio+Caniuqueo', rut: '11686509-2', empresa: 'Larrain', area: 'Elaborados'},
	{nombre: 'Jaime+Riquelme', rut: '18875071-0', empresa: 'Frigorifico+Temuco', area: 'Administracion'},
	{nombre: 'Kristofer+Soto', rut: '19058413-5', empresa: 'Frigorifico+Temuco', area: 'Faena'},
	{nombre: 'Leandro+Catalan', rut: '20643951-3', empresa: 'Frigorifico+Temuco', area: 'Elaborados'},
	{nombre: 'Diego+Illanes', rut: '16948315-9', empresa: 'Frigorifico+Temuco', area: 'SPC'},
	{nombre: 'Luis+Olivero', rut: '13732695-7', empresa: 'Otro', area: 'Transporte'},
	{nombre: 'Diego+Netle', rut: '19633696-6', empresa: 'Frigorifico+Temuco', area: 'Mantecion'},
	{nombre: 'Cristian+Campos', rut: '14035715-4', empresa: 'Frigorifico+Temuco', area: 'Mantencion'},
	{nombre: 'Jose+Alvarado', rut: '20367536-4', empresa: 'Larrain', area: 'Faena'},
	{nombre: 'Marisol+Castillo', rut: '12708709 -1', empresa: 'Frigorifico+Temuco', area: 'Desposte'},
	{nombre: 'Angel+Paez', rut: '26602324-3 ', empresa: 'Frigorifico+Temuco', area: 'Faena'},
	{nombre: 'Jose+Mendoza', rut: '9845971-5', empresa: 'Frigorifico+Temuco', area: 'Desposte'},
	{nombre: 'Patricio+Naipio', rut: '15240096-9', empresa: 'Frigorifico+Temuco', area: 'Faena'},
	{nombre: 'Alan+Martinez', rut: '16948619-0', empresa: 'Frigorifico+Temuco', area: 'Desposte'},
	{nombre: 'Johana+Catrileo', rut: '20107233-6', empresa: 'Casino', area: 'Casino'},
	{nombre: 'Raul+Lopez+Flores', rut: '10881789-5', empresa: 'Galdames', area: 'Faena'},
	{nombre: 'Luis+Chanqueo', rut: '11908214-5', empresa: 'Frigorifico+Temuco', area: 'Faena'},
	{nombre: 'Juan+Valdebenito', rut: '17766697-1', empresa: 'Frigorifico+Temuco', area: 'Faena'},
	{nombre: 'Carlos+Arancibia', rut: '8954552-8', empresa: 'Frigorifico+Temuco', area: 'Seguridad'},
	{nombre: 'Dayro+Ulloa', rut: '19766280-8', empresa: 'Larrain', area: 'Desposte'},
]